server:
  port: 8000
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: prod
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.uploadPath}
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    设置上传文件大小
servlet:
  multipart:
    max-file-size: 1000000Mb
    max-request-size: 1000000Mb
#配置mybatis-plus 开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:mapper/*.xml
#swgger加密
knife4j:
  enable: true
  basic:
    enable: true
    username: GPT-WEB-JAVA
    password: GPT-WEB-JAVA
#代理ip
broker:
  ip:
  port:
# 微信小程序配置
we-chat:
  #直连商户号
  mchid:
  #appid
  appId: ''
  #小程序 密钥
  secret: ''
# bing机器人请求路径
bingUrl: "http://XXXXXXXXX:3000/bing"



aliyun:
  sms:
    #AccessKey Id
    accessKeyId:
    #AccessKey Secret
    accessKeySecret:
    #api接口地址
    api:
    #短信模板CODE
    templateCode:
    #短信签名名称
    signName:
    #服务地址
    regionID:
